version: 2

updates:
  - package-ecosystem: npm
    directory: /server
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /renderer
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /electron
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
