export const PRODUCT_TOOL_CATALOG = [
  {
    name: "capability_search",
    description: "按当前任务搜索 App 能力。最多返回少量摘要,不会把全部 API 定义放入上下文。需要 App 中尚未直接提供为工具的能力时先调用。",
    safety: "read",
    domain: "capability",
  },
  {
    name: "capability_describe",
    description: "读取一个已搜索到的 App 能力详情和输入结构。只加载选中的单个能力,避免污染上下文。",
    safety: "read",
    domain: "capability",
  },
  {
    name: "capability_invoke",
    description: "调用 capability_search 找到的 App 能力。复用当前用户和项目权限;写入操作遵守当前审批模式。",
    safety: "execute",
    domain: "capability",
    confirm: true,
  },
  {
    name: "project_list",
    description: "列出当前用户可访问的问数项目/工作区,可按名称搜索。这是只读基础能力,可在任意工作区用于查看其他工作区。",
    safety: "read",
    domain: "project",
  },
  {
    name: "project_detail",
    description: "查看当前用户可访问的指定问数项目/工作区详情。可按 project_id/id 查看,也可按名称唯一匹配。这是只读基础能力,可在任意工作区使用。",
    safety: "read",
    domain: "project",
  },
  {
    name: "create_smart_qa_project",
    description: "创建新的智能问数项目/工作区,并把当前用户设为项目负责人。仅当用户本轮文本明确要求创建/新建/重建/转成/升级为智能问数项目或工作区时使用;不要从导入、统计或确认卡推导创建。",
    safety: "write",
    domain: "project",
    confirm: true,
  },
  {
    name: "project_create",
    description: "兼容旧名:创建新的智能问数项目/工作区。新流程优先使用 create_smart_qa_project;仅当用户本轮文本明确要求创建/新建/重建/转成/升级为智能问数项目或工作区时使用;不要从导入、统计或确认卡推导创建。",
    safety: "write",
    domain: "project",
    confirm: true,
  },
  {
    name: "project_session_move",
    description: "把当前 Agent 会话迁移到已有、现有、指定或具名问数项目。只能在用户本轮文本明确要求“把当前会话/对话迁移、移动或转到已有或具名问数项目/工作区”时使用;泛泛说转到智能问数应创建新项目,普通文件分析、发票统计、导入数据和确认卡都不能触发。",
    safety: "write",
    domain: "project",
    confirm: true,
  },
  {
    name: "file_classify",
    description: "识别本地文件或目录中的数据文件类型,按数据库文件、结构化文件、非结构化文档分组。",
    safety: "read",
    domain: "file",
  },
  {
    name: "structured_import",
    description: "把 CSV/Excel/JSON/Parquet 等结构化文件导入项目,生成 DuckDB 连接和表字段元数据。",
    safety: "write",
    domain: "structured",
    confirm: true,
  },
  {
    name: "database_file_import",
    description: "把本地 SQLite 或 DuckDB 文件导入项目,创建数据库连接并同步 schema。",
    safety: "write",
    domain: "database",
    confirm: true,
  },
  {
    name: "unstructured_import",
    description: "把 Markdown/PDF/DOCX/TXT 等非结构化文档导入项目,提交后台 Markdown 转换或图片识别。",
    safety: "write",
    domain: "unstructured",
    confirm: true,
    long_running: true,
  },
  {
    name: "job_status",
    description: "查询导入、文档解析、schema 同步等数据准备任务的当前状态和摘要。",
    safety: "read",
    domain: "job",
  },
  {
    name: "query_smoke_test",
    description: "对已导入的数据库连接执行轻量只读 smoke test,验证表可查询。",
    safety: "read",
    domain: "query",
  },
  {
    name: "skill_list",
    description: "列出 App 级 Skill Library 中的技能定义。项目上下文中调用时仍然读取 App 级定义。",
    safety: "read",
    domain: "skill",
  },
  {
    name: "skill_registry_search",
    description: "在受信任的公开 GitHub Skill 仓库中按名称查找 Skill。只读取目录，不会下载或安装。返回可审计的仓库、路径和源码地址。",
    safety: "read",
    domain: "skill",
  },
  {
    name: "skill_download",
    description: "从 skill_registry_search 返回的 GitHub SKILL.md 地址下载并写入 App Skill Library。只导入说明文本，不执行仓库代码；可为小程序加入受控的产品数据读写适配。需要用户确认。",
    safety: "write",
    domain: "skill",
    confirm: true,
  },
  {
    name: "skill_create",
    description: "创建 App 级 Skill 定义。不会创建项目私有 Skill;如需当前项目使用,创建后再调用 project_skill_enable。",
    safety: "write",
    domain: "skill",
    confirm: true,
  },
  {
    name: "skill_update",
    description: "更新 App 级自定义 Skill 定义。内置 Skill 不支持编辑定义。",
    safety: "write",
    domain: "skill",
    confirm: true,
  },
  {
    name: "skill_toggle",
    description: "更新 App 级 Skill 总开关或默认启用状态。is_active=false 会让所有项目都不可执行该 Skill。",
    safety: "write",
    domain: "skill",
    confirm: true,
  },
  {
    name: "skill_delete",
    description: "软删除 App 级自定义 Skill 定义。内置 Skill 不可删除。",
    safety: "write",
    domain: "skill",
    confirm: true,
  },
  {
    name: "project_skill_list",
    description: "查看当前或指定问数项目的 effective skills,包括 App 默认状态和项目绑定状态。",
    safety: "read",
    domain: "skill",
  },
  {
    name: "project_skill_enable",
    description: "在当前或指定问数项目中启用一个 App Skill。",
    safety: "write",
    domain: "skill",
    confirm: true,
  },
  {
    name: "project_skill_disable",
    description: "在当前或指定问数项目中禁用一个 App Skill。",
    safety: "write",
    domain: "skill",
    confirm: true,
  },
  {
    name: "mcp_provider_list",
    description: "列出 App 级 MCP Provider Library 中的 Provider 定义。",
    safety: "read",
    domain: "mcp",
  },
  {
    name: "mcp_provider_create",
    description: "创建 App 级 MCP Provider 定义。不会创建项目私有 Provider;如需当前项目使用,创建后再调用 project_mcp_provider_enable。",
    safety: "write",
    domain: "mcp",
    confirm: true,
  },
  {
    name: "mcp_provider_update",
    description: "更新 App 级 MCP Provider 定义,包括 command、args、env 和默认启用状态。",
    safety: "write",
    domain: "mcp",
    confirm: true,
  },
  {
    name: "mcp_provider_toggle",
    description: "更新 App 级 MCP Provider 总开关或默认启用状态。is_active=false 会让所有项目都不可执行该 Provider。",
    safety: "write",
    domain: "mcp",
    confirm: true,
  },
  {
    name: "mcp_provider_delete",
    description: "软删除 App 级 MCP Provider 定义。",
    safety: "write",
    domain: "mcp",
    confirm: true,
  },
  {
    name: "mcp_provider_test",
    description: "用给定 command/args/env 临时连接 MCP Provider 并列出工具。会启动本地命令。",
    safety: "execute",
    domain: "mcp",
    confirm: true,
  },
  {
    name: "mcp_provider_rediscover",
    description: "重新连接 App 级 MCP Provider 并刷新工具发现状态。",
    safety: "execute",
    domain: "mcp",
    confirm: true,
  },
  {
    name: "project_mcp_provider_list",
    description: "查看当前或指定问数项目的 effective MCP Providers,包括 App 默认状态和项目绑定状态。",
    safety: "read",
    domain: "mcp",
  },
  {
    name: "project_mcp_provider_enable",
    description: "在当前或指定问数项目中启用一个 App MCP Provider。",
    safety: "write",
    domain: "mcp",
    confirm: true,
  },
  {
    name: "project_mcp_provider_disable",
    description: "在当前或指定问数项目中禁用一个 App MCP Provider。",
    safety: "write",
    domain: "mcp",
    confirm: true,
  },
  {
    name: "project_mcp_provider_reset",
    description: "清除当前或指定问数项目的 MCP Provider 启用覆盖,恢复继承 App 默认状态。",
    safety: "write",
    domain: "mcp",
    confirm: true,
  },
  {
    name: "ui_module_list",
    description: "列出当前用户已经安装或停用的动态界面模块,包括侧边栏位置和当前版本。",
    safety: "read",
    domain: "ui_module",
  },
  {
    name: "ui_module_get",
    description: "读取一个动态界面模块的完整页面、动作和版本定义。",
    safety: "read",
    domain: "ui_module",
  },
  {
    name: "ui_skill_product_draft_create",
    description: "兼容旧 Skill Product 的专用入口，会生成 Skill 运行时绑定。只用于维护旧产品；新小程序即使参考 Skill，也应使用 ui_module_draft_create。",
    safety: "write",
    domain: "ui_module",
  },
  {
    name: "ui_module_draft_create",
    description: "通用小程序构建入口。把对话、Skill、文档或参考产品统一作为需求来源，生成页面、受控动作、状态和 MiniApp Package。Skill 只是需求模板，不会自动创建 Agent 绑定。只生成草稿，不会直接改变侧边栏。",
    safety: "write",
    domain: "ui_module",
  },
  {
    name: "ui_module_draft_validate",
    description: "检查动态界面模块草稿的组件、动作、权限和大小是否安全可运行。",
    safety: "read",
    domain: "ui_module",
  },
  {
    name: "ui_module_draft_preview",
    description: "打开动态界面模块草稿预览。预览只使用草稿或模拟数据,不会安装模块。",
    safety: "read",
    domain: "ui_module",
  },
  {
    name: "ui_module_draft_install",
    description: "把已经检查和预览过的动态界面模块草稿安装为不可变版本,并更新侧边栏。必须原样传入预览返回的 expected_revision、validation_hash 和 preview_token;安装前必须得到用户确认。",
    safety: "write",
    domain: "ui_module",
    confirm: true,
  },
  {
    name: "miniapp_agent_export_draft",
    description: "从已经安装的小程序中选择少量受控动作，生成独立的 Agent 能力草稿。不会自动发布，也不会把整个小程序交给主 Agent。",
    safety: "write",
    domain: "ui_module",
  },
  {
    name: "miniapp_agent_export_validate",
    description: "检查 Agent 能力草稿绑定的小程序版本、动作、输入结构、权限和确认规则。",
    safety: "read",
    domain: "ui_module",
  },
  {
    name: "miniapp_agent_export_publish",
    description: "发布检查通过的小程序 Agent 能力。发布后主 Agent 才能发现和调用选中的命令。",
    safety: "write",
    domain: "ui_module",
    confirm: true,
  },
  {
    name: "miniapp_agent_export_suspend",
    description: "停用一个已经发布的小程序 Agent 能力；小程序页面和数据仍保留，用户仍可手动使用。",
    safety: "write",
    domain: "ui_module",
    confirm: true,
  },
  {
    name: "miniapp_list",
    description: "列出小程序发布给主 Agent 的能力及当前是否可调用。默认只列已发布能力。",
    safety: "read",
    domain: "ui_module",
  },
  {
    name: "miniapp_use",
    description: "调用一个已经发布的小程序命令。只能执行用户选择公开的动作，并复用小程序当前版本、权限和执行记录。",
    safety: "execute",
    domain: "ui_module",
    confirm: true,
  },
  {
    name: "miniapp_open",
    description: "打开已安装小程序的指定页面，可带上 miniapp_use 返回的 invocation_id 接力同一次任务。",
    safety: "read",
    domain: "ui_module",
  },
  {
    name: "ui_module_toggle",
    description: "启用或停用一个动态界面模块。停用后从侧边栏隐藏,数据和版本仍保留。",
    safety: "write",
    domain: "ui_module",
    confirm: true,
  },
  {
    name: "ui_module_rollback",
    description: "把动态界面模块切换回一个已经安装的旧版本。",
    safety: "write",
    domain: "ui_module",
    confirm: true,
  },
];

export const PRODUCT_TOOL_NAMES = new Set(PRODUCT_TOOL_CATALOG.map((t) => t.name));
export const PRODUCT_CONFIRM_TOOL_NAMES = new Set(PRODUCT_TOOL_CATALOG.filter((t) => t.confirm).map((t) => t.name));
