/**
 * Element Plus 图标名 → Tabler 图标组件 的映射(对齐 @element-plus/icons-vue 的用法)。
 * 原工程在 router meta(elSvgIcon)与各组件里用 EP 图标名；这里集中映射到 @tabler/icons-react。
 * 未命中的名字回退到 IconPoint。
 */
import {
  IconTarget,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowBackUp,
  IconBell,
  IconBox,
  IconBriefcase,
  IconCalendar,
  IconCaretDownFilled,
  IconMessageDots,
  IconMessage2,
  IconCheck,
  IconCircleCheck,
  IconCircleCheckFilled,
  IconCircleX,
  IconCircleXFilled,
  IconClock,
  IconX,
  IconCoin,
  IconStack2,
  IconPlugConnected,
  IconCopy,
  IconCpu,
  IconChartHistogram,
  IconLayoutDashboard,
  IconChartLine,
  IconChartPie,
  IconChartBar,
  IconTable,
  IconTrash,
  IconFileText,
  IconDownload,
  IconPencil,
  IconLayoutSidebarLeftExpand,
  IconFiles,
  IconFolder,
  IconFolderOpen,
  IconMaximize,
  IconLayoutGrid,
  IconInfoCircleFilled,
  IconKey,
  IconLink,
  IconList,
  IconLoader2,
  IconLock,
  IconWand,
  IconMenu2,
  IconCash,
  IconDots,
  IconPlus,
  IconLocation,
  IconSend,
  IconHelpCircleFilled,
  IconArrowsSort,
  IconBook,
  IconRefresh,
  IconCircleMinus,
  IconSearch,
  IconSettings,
  IconAdjustments,
  IconShare,
  IconStar,
  IconSun,
  IconArrowsExchange,
  IconPower,
  IconTicket,
  IconTool,
  IconTrendingUp,
  IconUpload,
  IconCloudUpload,
  IconUser,
  IconUserFilled,
  IconPlayerPause,
  IconEye,
  IconAlertTriangle,
  IconAlertTriangleFilled,
  IconZoomIn,
  IconZoomOut,
  IconPoint,
  type IconProps
} from '@tabler/icons-react'
import type { FC } from 'react'

export type TablerIcon = FC<IconProps>

export const EP_ICON_MAP: Record<string, TablerIcon> = {
  Aim: IconTarget,
  ArrowDown: IconArrowDown,
  ArrowLeft: IconArrowLeft,
  ArrowRight: IconArrowRight,
  ArrowUp: IconArrowUp,
  Back: IconArrowBackUp,
  Bell: IconBell,
  Box: IconBox,
  Briefcase: IconBriefcase,
  Calendar: IconCalendar,
  CaretBottom: IconCaretDownFilled,
  ChatDotRound: IconMessageDots,
  ChatDotSquare: IconMessage2,
  Check: IconCheck,
  CircleCheck: IconCircleCheck,
  CircleCheckFilled: IconCircleCheckFilled,
  CircleClose: IconCircleX,
  CircleCloseFilled: IconCircleXFilled,
  Clock: IconClock,
  Close: IconX,
  Coin: IconCoin,
  Collection: IconStack2,
  Connection: IconPlugConnected,
  CopyDocument: IconCopy,
  Cpu: IconCpu,
  DataAnalysis: IconChartHistogram,
  DataBoard: IconLayoutDashboard,
  DataLine: IconChartLine,
  PieChart: IconChartPie,
  Histogram: IconChartBar,
  Grid3x3: IconTable,
  Delete: IconTrash,
  Document: IconFileText,
  DocumentCopy: IconCopy,
  Download: IconDownload,
  Edit: IconPencil,
  EditPen: IconPencil,
  Expand: IconLayoutSidebarLeftExpand,
  Files: IconFiles,
  Folder: IconFolder,
  FolderOpened: IconFolderOpen,
  FullScreen: IconMaximize,
  Grid: IconLayoutGrid,
  InfoFilled: IconInfoCircleFilled,
  Key: IconKey,
  Link: IconLink,
  List: IconList,
  Loading: IconLoader2,
  Lock: IconLock,
  MagicStick: IconWand,
  Menu: IconMenu2,
  Message: IconMessage2,
  Money: IconCash,
  MoreFilled: IconDots,
  Plus: IconPlus,
  Position: IconLocation,
  Promotion: IconSend,
  QuestionFilled: IconHelpCircleFilled,
  Rank: IconArrowsSort,
  Reading: IconBook,
  Refresh: IconRefresh,
  RefreshLeft: IconRefresh,
  RefreshRight: IconRefresh,
  RemoveFilled: IconCircleMinus,
  Search: IconSearch,
  Select: IconCheck,
  Setting: IconSettings,
  SetUp: IconAdjustments,
  Share: IconShare,
  Sort: IconArrowsSort,
  Star: IconStar,
  Sunny: IconSun,
  Switch: IconArrowsExchange,
  SwitchButton: IconPower,
  Tickets: IconTicket,
  Tools: IconTool,
  TrendCharts: IconTrendingUp,
  Upload: IconUpload,
  UploadFilled: IconCloudUpload,
  User: IconUser,
  UserFilled: IconUserFilled,
  VideoPause: IconPlayerPause,
  View: IconEye,
  Warning: IconAlertTriangle,
  WarningFilled: IconAlertTriangleFilled,
  ZoomIn: IconZoomIn,
  ZoomOut: IconZoomOut
}

export const resolveEpIcon = (name?: string): TablerIcon => (name && EP_ICON_MAP[name]) || IconPoint
