import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { mkdir, readFile, rename, stat, writeFile } from 'node:fs/promises';

function quoteIdentifier(value) {
  return `"${String(value || '').replaceAll('"', '""')}"`;
}

function sqlComment(value, maxLength = 600) {
  const text = String(value || '').replace(/\r?\n/g, ' ').trim();
  return text.length > maxLength ? `${text.slice(0, maxLength).trimEnd()}…` : text;
}

function safeType(value) {
  const type = String(value || 'TEXT').trim();
  return /^[\p{L}\p{N}_ (),.\[\]-]+$/u.test(type) ? type : 'TEXT';
}

export function schemaFilePath(projectId, connectionId) {
  const projectsDir = process.env.YIW_PROJECTS_DIR || join(homedir(), '.yiw', 'projects');
  return join(projectsDir, String(projectId), 'schemas', `${connectionId}.sql`);
}

export function buildSchemaSql({ connection, tables, relationships = [] }) {
  const lines = [
    '-- YiW database schema snapshot',
    '-- Generated from table_metadata and column_metadata. Do not edit this file directly.',
    `-- Connection: ${sqlComment(connection?.name || connection?.id || '')}`,
    `-- Database type: ${sqlComment(connection?.db_type || '')}`,
    `-- Generated at: ${new Date().toISOString()}`,
    '',
  ];

  for (const table of tables || []) {
    const schemaName = table.schema_name && table.schema_name !== 'default' ? table.schema_name : null;
    const fullName = schemaName
      ? `${quoteIdentifier(schemaName)}.${quoteIdentifier(table.table_name)}`
      : quoteIdentifier(table.table_name);
    if (table.is_view) lines.push('-- Source object type: VIEW');
    if (table.description) lines.push(`-- Table description: ${sqlComment(table.description)}`);
    if (table.keywords) lines.push(`-- Table keywords: ${sqlComment(table.keywords)}`);
    lines.push(`CREATE TABLE ${fullName} (`);
    const columns = table.columns || [];
    columns.forEach((column, index) => {
      const parts = [quoteIdentifier(column.column_name), safeType(column.data_type)];
      if (column.is_primary_key) parts.push('PRIMARY KEY');
      if (column.is_nullable === false || column.is_nullable === 0) parts.push('NOT NULL');
      if (column.is_unique) parts.push('UNIQUE');
      if (column.default_value !== null && column.default_value !== undefined && column.default_value !== '') {
        parts.push(`DEFAULT ${String(column.default_value)}`);
      }
      const suffix = index === columns.length - 1 ? '' : ',';
      const notes = [];
      if (column.description) notes.push(`description=${sqlComment(column.description)}`);
      if (column.keywords) notes.push(`keywords=${sqlComment(column.keywords)}`);
      if (column.example_values) notes.push(`examples=${sqlComment(column.example_values, 300)}`);
      if (column.enum_mappings) notes.push(`enum=${sqlComment(column.enum_mappings, 600)}`);
      const comment = notes.length ? ` -- ${notes.join('; ')}` : '';
      lines.push(`  ${parts.join(' ')}${suffix}${comment}`);
    });
    lines.push(');', '');
  }
  if (relationships.length) {
    lines.push('-- Table relationships');
    for (const relationship of relationships) {
      const sourceTable = [relationship.source_schema, relationship.source_table].filter(Boolean).join('.');
      const targetTable = [relationship.target_schema, relationship.target_table].filter(Boolean).join('.');
      const notes = [relationship.relationship_type, relationship.constraint_name, relationship.description]
        .map((value) => sqlComment(value))
        .filter(Boolean)
        .join('; ');
      lines.push(
        `-- Relationship: ${sourceTable}.${relationship.source_column} -> ${targetTable}.${relationship.target_column}`
        + (notes ? `; ${notes}` : ''),
      );
    }
    lines.push('');
  }
  return `${lines.join('\n').trim()}\n`;
}

async function readMetadataTables(ctx, connectionId) {
  const tables = await ctx.query(
    `SELECT id, schema_name, table_name, table_type, description, keywords, is_view
       FROM table_metadata
      WHERE database_connection_id=$1 AND deleted_at IS NULL
      ORDER BY schema_name, table_name`,
    [connectionId],
  );
  for (const table of tables) {
    table.columns = await ctx.query(
      `SELECT column_name, data_type, description, keywords, example_values, enum_mappings,
              is_nullable, default_value, is_primary_key, is_foreign_key, is_unique, is_indexed
         FROM column_metadata
        WHERE table_id=$1 AND deleted_at IS NULL
        ORDER BY created_at, column_name`,
      [table.id],
    );
  }
  return tables;
}

async function readMetadataRelationships(ctx, connectionId) {
  return ctx.query(
    `SELECT r.source_column, r.target_column, r.relationship_type, r.constraint_name, r.description,
            st.schema_name AS source_schema, st.table_name AS source_table,
            tt.schema_name AS target_schema, tt.table_name AS target_table
       FROM relationship_metadata r
       JOIN table_metadata st ON st.id = r.source_table_id AND st.deleted_at IS NULL
       JOIN table_metadata tt ON tt.id = r.target_table_id AND tt.deleted_at IS NULL
      WHERE r.database_connection_id=$1 AND r.deleted_at IS NULL
      ORDER BY st.schema_name, st.table_name, r.source_column, tt.schema_name, tt.table_name, r.target_column`,
    [connectionId],
  ).catch(() => []);
}

export async function writeSchemaSnapshot(ctx, { projectId = null, connectionId, connection = null }) {
  const conn = connection || await ctx.queryOne(
    `SELECT id, project_id, name, db_type FROM database_connections WHERE id=$1 AND deleted_at IS NULL`,
    [connectionId],
  );
  if (!conn) throw new Error(`数据库连接不存在: ${connectionId}`);
  const [tables, relationships] = await Promise.all([
    readMetadataTables(ctx, connectionId),
    readMetadataRelationships(ctx, connectionId),
  ]);
  const effectiveProjectId = projectId || conn.project_id;
  if (!effectiveProjectId) throw new Error(`数据库连接缺少 project_id: ${connectionId}`);
  const path = schemaFilePath(effectiveProjectId, connectionId);
  await mkdir(dirname(path), { recursive: true });
  const sql = buildSchemaSql({ connection: conn, tables, relationships });
  const tempPath = `${path}.tmp`;
  await writeFile(tempPath, sql, 'utf8');
  await rename(tempPath, path);
  return { path, sql, tableCount: tables.length };
}

async function latestSchemaMetadataTime(ctx, connectionId) {
  const [tableUpdate, columnUpdate, relationshipUpdate] = await Promise.all([
    ctx.queryOne(
      `SELECT MAX(updated_at) AS updated_at FROM table_metadata
        WHERE database_connection_id=$1 AND deleted_at IS NULL`,
      [connectionId],
    ).catch(() => null),
    ctx.queryOne(
      `SELECT MAX(c.updated_at) AS updated_at
         FROM column_metadata c JOIN table_metadata t ON c.table_id=t.id
        WHERE t.database_connection_id=$1 AND c.deleted_at IS NULL AND t.deleted_at IS NULL`,
      [connectionId],
    ).catch(() => null),
    ctx.queryOne(
      `SELECT MAX(updated_at) AS updated_at FROM relationship_metadata
        WHERE database_connection_id=$1 AND deleted_at IS NULL`,
      [connectionId],
    ).catch(() => null),
  ]);
  return Math.max(
    Date.parse(tableUpdate?.updated_at || 0) || 0,
    Date.parse(columnUpdate?.updated_at || 0) || 0,
    Date.parse(relationshipUpdate?.updated_at || 0) || 0,
  );
}

/**
 * 在线问答只读检查：不会生成、刷新或修改 Schema 文件。
 * 离线任务负责 writeSchemaSnapshot；这里仅报告 ready / stale / missing。
 */
export async function inspectSchemaSnapshot(ctx, { projectId, connectionId, connection = null }) {
  const conn = connection || await ctx.queryOne(
    `SELECT id, project_id, name, db_type FROM database_connections WHERE id=$1 AND deleted_at IS NULL`,
    [connectionId],
  );
  const effectiveProjectId = projectId || conn?.project_id;
  if (!effectiveProjectId) throw new Error(`数据库连接缺少 project_id: ${connectionId}`);
  const path = schemaFilePath(effectiveProjectId, connectionId);
  const fileInfo = await stat(path).catch(() => null);
  if (!fileInfo?.isFile()) {
    return { status: 'missing', path, sql: '', tableCount: 0, generatedAt: null, metadataUpdatedAt: null };
  }
  const sql = await readFile(path, 'utf8').catch(() => '');
  if (!sql.trim()) {
    return { status: 'missing', path, sql: '', tableCount: 0, generatedAt: fileInfo.mtime.toISOString(), metadataUpdatedAt: null };
  }
  const metadataTime = await latestSchemaMetadataTime(ctx, connectionId);
  return {
    status: metadataTime > fileInfo.mtimeMs ? 'stale' : 'ready',
    path,
    sql,
    tableCount: (sql.match(/\bCREATE\s+(?:TABLE|VIEW)\b/gi) || []).length,
    generatedAt: fileInfo.mtime.toISOString(),
    metadataUpdatedAt: metadataTime ? new Date(metadataTime).toISOString() : null,
  };
}

export async function loadSchemaSnapshot(ctx, { projectId, connectionId, connection = null }) {
  const conn = connection || await ctx.queryOne(
    `SELECT id, project_id, name, db_type FROM database_connections WHERE id=$1 AND deleted_at IS NULL`,
    [connectionId],
  );
  const effectiveProjectId = projectId || conn?.project_id;
  if (!effectiveProjectId) throw new Error(`数据库连接缺少 project_id: ${connectionId}`);
  const path = schemaFilePath(effectiveProjectId, connectionId);
  try {
    const [fileInfo, latestMetadataTime] = await Promise.all([
      stat(path),
      latestSchemaMetadataTime(ctx, connectionId),
    ]);
    if (latestMetadataTime > fileInfo.mtimeMs) {
      return writeSchemaSnapshot(ctx, { projectId: effectiveProjectId, connectionId, connection: conn });
    }
    const sql = await readFile(path, 'utf8');
    if (sql.trim()) return { path, sql, tableCount: (sql.match(/\bCREATE\s+(?:TABLE|VIEW)\b/gi) || []).length };
  } catch { /* 旧项目首次使用时从本地元数据补写 */ }
  return writeSchemaSnapshot(ctx, { projectId: effectiveProjectId, connectionId, connection: conn });
}
